import { colors, fontSize, spacing, radius, font } from '../../utils/theme'

export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xl,
  },
  topBar: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
  btnPrimary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacing.sm,
    padding: `${spacing.sm + 4}px ${spacing.lg}px`,
    borderRadius: radius.md,
    background: colors.blue,
    color: 'white',
    fontWeight: font.weight.semibold,
    fontSize: fontSize.md,
    border: 'none',
    cursor: 'pointer',
    fontFamily: font.sans,
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
  },
  annonceCard: (expire) => ({
    background: colors.surface,
    border: `1px solid ${expire ? 'rgba(244,98,42,0.15)' : 'rgba(91,163,245,0.12)'}`,
    borderRadius: radius.xl,
    padding: spacing.xl,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
    opacity: expire ? 0.6 : 1,
  }),
  annonceHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  annonceTitre: {
    fontSize: fontSize.lg,
    fontWeight: font.weight.bold,
    color: colors.text,
  },
  annonceContenu: {
    fontSize: fontSize.md,
    color: colors.textMuted,
    lineHeight: 1.6,
  },
  annonceMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  badge: (bg, color) => ({
    padding: '3px 10px',
    borderRadius: radius.full,
    background: bg,
    color: color,
    fontSize: fontSize.xs,
    fontWeight: font.weight.semibold,
  }),
  metaDate: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
  },
  emptyState: {
    textAlign: 'center',
    padding: `${spacing.xxl}px`,
    color: colors.textMuted,
    fontSize: fontSize.md,
    background: colors.surface,
    borderRadius: radius.xl,
    border: `1px solid rgba(91,163,245,0.08)`,
  },
  // Modal
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: spacing.lg,
  },
  modal: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.12)`,
    borderRadius: radius.xl,
    padding: spacing.xl,
    width: '100%',
    maxWidth: '500px',
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontSize: fontSize.lg,
    fontWeight: font.weight.bold,
    color: colors.text,
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: colors.textMuted,
    display: 'flex',
    padding: spacing.xs,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  label: {
    fontSize: fontSize.sm,
    fontWeight: font.weight.medium,
    color: colors.textMuted,
  },
  input: {
    width: '100%',
    padding: `${spacing.sm + 4}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: colors.surface2,
    border: `1px solid rgba(91,163,245,0.15)`,
    color: colors.text,
    fontSize: fontSize.md,
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: font.sans,
  },
  textarea: {
    width: '100%',
    padding: `${spacing.sm + 4}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: colors.surface2,
    border: `1px solid rgba(91,163,245,0.15)`,
    color: colors.text,
    fontSize: fontSize.md,
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: font.sans,
    resize: 'vertical',
    minHeight: '100px',
  },
  hint: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    marginTop: '4px',
  },
  btnSubmit: {
    width: '100%',
    padding: `${spacing.sm + 6}px`,
    borderRadius: radius.md,
    background: colors.blue,
    color: 'white',
    fontWeight: font.weight.semibold,
    fontSize: fontSize.md,
    border: 'none',
    cursor: 'pointer',
    fontFamily: font.sans,
  },
  erreur: {
    padding: `${spacing.sm + 4}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: 'rgba(244,98,42,0.1)',
    border: '1px solid rgba(244,98,42,0.3)',
    color: colors.error,
    fontSize: fontSize.sm,
  },
}
