import { colors, fontSize, spacing, radius, font } from '../../utils/theme'

export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xl,
  },
  topBar: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  searchWrapper: {
    position: 'relative',
    flex: 1,
    minWidth: '200px',
  },
  searchIcon: {
    position: 'absolute',
    left: '14px',
    top: '50%',
    transform: 'translateY(-50%)',
    color: colors.textMuted,
    pointerEvents: 'none',
  },
  searchInput: {
    width: '100%',
    padding: `${spacing.sm + 4}px ${spacing.md}px ${spacing.sm + 4}px 42px`,
    borderRadius: radius.md,
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.12)`,
    color: colors.text,
    fontSize: fontSize.md,
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: font.sans,
  },
  filterBtn: (active) => ({
    padding: `${spacing.sm + 2}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: active ? 'rgba(42,125,225,0.15)' : colors.surface,
    border: active ? `1px solid rgba(42,125,225,0.3)` : `1px solid rgba(91,163,245,0.12)`,
    color: active ? colors.blueLight : colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: active ? font.weight.semibold : font.weight.regular,
    cursor: 'pointer',
    fontFamily: font.sans,
    whiteSpace: 'nowrap',
  }),
  count: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
  },
  table: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  row: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.08)`,
    borderRadius: radius.lg,
    padding: `${spacing.md}px ${spacing.lg}px`,
    display: 'grid',
    gridTemplateColumns: '40px 1fr 120px 100px 80px',
    alignItems: 'center',
    gap: spacing.md,
    cursor: 'pointer',
    transition: 'border-color 0.15s',
  },
  rowMobile: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.08)`,
    borderRadius: radius.lg,
    padding: spacing.md,
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
    cursor: 'pointer',
  },
  avatar: (color) => ({
    width: '40px',
    height: '40px',
    borderRadius: radius.full,
    background: color,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: font.weight.bold,
    fontSize: fontSize.md,
    flexShrink: 0,
  }),
  clientName: {
    fontSize: fontSize.md,
    fontWeight: font.weight.semibold,
    color: colors.text,
  },
  clientPhone: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    marginTop: '2px',
  },
  badge: (bg, color) => ({
    padding: '3px 10px',
    borderRadius: radius.full,
    background: bg,
    color: color,
    fontSize: fontSize.xs,
    fontWeight: font.weight.semibold,
    display: 'inline-block',
  }),
  points: {
    fontSize: fontSize.sm,
    color: colors.text,
    fontWeight: font.weight.semibold,
    textAlign: 'center',
  },
  pointsSub: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    textAlign: 'center',
  },
  emptyState: {
    textAlign: 'center',
    padding: `${spacing.xxl}px`,
    color: colors.textMuted,
    fontSize: fontSize.md,
    background: colors.surface,
    borderRadius: radius.xl,
    border: `1px solid rgba(91,163,245,0.08)`,
  },
  // Modal détail client
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: spacing.lg,
  },
  modal: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.12)`,
    borderRadius: radius.xl,
    padding: spacing.xl,
    width: '100%',
    maxWidth: '480px',
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
    maxHeight: '80vh',
    overflowY: 'auto',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontSize: fontSize.lg,
    fontWeight: font.weight.bold,
    color: colors.text,
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: colors.textMuted,
    display: 'flex',
    padding: spacing.xs,
  },
  carteInfo: {
    background: colors.surface2,
    borderRadius: radius.md,
    padding: spacing.lg,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
  },
  carteRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  carteLabel: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
  },
  carteValue: {
    fontSize: fontSize.sm,
    color: colors.text,
    fontWeight: font.weight.semibold,
  },
  btnDanger: {
    padding: `${spacing.sm}px ${spacing.lg}px`,
    borderRadius: radius.md,
    background: 'rgba(244,98,42,0.1)',
    border: '1px solid rgba(244,98,42,0.25)',
    color: colors.orangeLight,
    fontSize: fontSize.sm,
    fontWeight: font.weight.semibold,
    cursor: 'pointer',
    fontFamily: font.sans,
  },
  btnPrimary: {
    padding: `${spacing.sm}px ${spacing.lg}px`,
    borderRadius: radius.md,
    background: colors.blue,
    color: 'white',
    fontSize: fontSize.sm,
    fontWeight: font.weight.semibold,
    cursor: 'pointer',
    fontFamily: font.sans,
    border: 'none',
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacing.sm,
  },
}
