import { colors, fontSize, spacing, radius, font } from '../../utils/theme'

export const styles = {
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: spacing.lg,
    marginBottom: spacing.xl,
  },
  statCard: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.12)`,
    borderRadius: radius.xl,
    padding: spacing.lg,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  statLabel: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    fontWeight: font.weight.medium,
  },
  statValue: {
    fontSize: fontSize.title,
    fontWeight: font.weight.bold,
    color: colors.text,
    letterSpacing: '-1px',
  },
  statSub: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
  },
  statIcon: (bg) => ({
    width: '40px',
    height: '40px',
    borderRadius: radius.md,
    background: bg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xs,
  }),
  section: {
    marginBottom: spacing.xl,
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.lg,
  },
  sectionTitle: {
    fontSize: fontSize.lg,
    fontWeight: font.weight.bold,
    color: colors.text,
  },
  seeAll: {
    fontSize: fontSize.sm,
    color: colors.blueLight,
    textDecoration: 'none',
    fontWeight: font.weight.medium,
  },
  clientCard: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.08)`,
    borderRadius: radius.lg,
    padding: spacing.lg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  clientInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
  },
  avatar: (color) => ({
    width: '40px',
    height: '40px',
    borderRadius: radius.full,
    background: color,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: font.weight.bold,
    fontSize: fontSize.md,
    flexShrink: 0,
  }),
  clientName: {
    fontSize: fontSize.md,
    fontWeight: font.weight.semibold,
    color: colors.text,
  },
  clientSub: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    marginTop: '2px',
  },
  badge: (bg, color) => ({
    padding: `4px 10px`,
    borderRadius: radius.full,
    background: bg,
    color: color,
    fontSize: fontSize.xs,
    fontWeight: font.weight.semibold,
  }),
  emptyState: {
    textAlign: 'center',
    padding: `${spacing.xxl}px ${spacing.lg}px`,
    color: colors.textMuted,
    fontSize: fontSize.md,
  },
  qrSection: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.12)`,
    borderRadius: radius.xl,
    padding: spacing.xl,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.lg,
  },
  qrInfo: {
    flex: 1,
  },
  qrTitle: {
    fontSize: fontSize.lg,
    fontWeight: font.weight.bold,
    color: colors.text,
    marginBottom: spacing.xs,
  },
  qrSub: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    lineHeight: 1.5,
  },
  qrImage: {
    width: '100px',
    height: '100px',
    borderRadius: radius.md,
    background: 'white',
    padding: '8px',
  },
  btnPrimary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacing.sm,
    padding: `${spacing.sm}px ${spacing.lg}px`,
    borderRadius: radius.md,
    background: colors.blue,
    color: 'white',
    fontWeight: font.weight.semibold,
    fontSize: fontSize.sm,
    border: 'none',
    cursor: 'pointer',
    textDecoration: 'none',
    marginTop: spacing.md,
    fontFamily: font.sans,
  },
}
