import { colors, fontSize, spacing, radius, font } from '../../utils/theme'

export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xl,
    maxWidth: '600px',
  },
  card: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.12)`,
    borderRadius: radius.xl,
    padding: spacing.xl,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  cardTitle: {
    fontSize: fontSize.lg,
    fontWeight: font.weight.bold,
    color: colors.text,
    paddingBottom: spacing.sm,
    borderBottom: `1px solid rgba(91,163,245,0.08)`,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  row: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: spacing.md,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  label: {
    fontSize: fontSize.sm,
    fontWeight: font.weight.medium,
    color: colors.textMuted,
  },
  input: {
    width: '100%',
    padding: `${spacing.sm + 4}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: colors.surface2,
    border: `1px solid rgba(91,163,245,0.15)`,
    color: colors.text,
    fontSize: fontSize.md,
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: font.sans,
  },
  inputWrapper: {
    position: 'relative',
    width: '100%',
  },
  eyeBtn: {
    position: 'absolute',
    right: '14px',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: colors.textMuted,
    display: 'flex',
    alignItems: 'center',
    padding: 0,
  },
  colorRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
  },
  colorPreview: {
    width: '44px',
    height: '44px',
    borderRadius: radius.md,
    border: `1px solid rgba(91,163,245,0.15)`,
    flexShrink: 0,
    cursor: 'pointer',
  },
  uploadZone: {
    border: `2px dashed rgba(91,163,245,0.2)`,
    borderRadius: radius.md,
    padding: spacing.lg,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: spacing.sm,
    cursor: 'pointer',
  },
  uploadPreview: {
    width: '64px',
    height: '64px',
    borderRadius: radius.md,
    objectFit: 'cover',
  },
  uploadText: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    textAlign: 'center',
  },
  btnPrimary: {
    padding: `${spacing.sm + 4}px ${spacing.xl}px`,
    borderRadius: radius.md,
    background: colors.blue,
    color: 'white',
    fontWeight: font.weight.semibold,
    fontSize: fontSize.md,
    border: 'none',
    cursor: 'pointer',
    fontFamily: font.sans,
    alignSelf: 'flex-start',
  },
  btnDanger: {
    padding: `${spacing.sm + 4}px ${spacing.xl}px`,
    borderRadius: radius.md,
    background: 'rgba(244,98,42,0.1)',
    border: '1px solid rgba(244,98,42,0.3)',
    color: colors.orangeLight,
    fontWeight: font.weight.semibold,
    fontSize: fontSize.md,
    cursor: 'pointer',
    fontFamily: font.sans,
    alignSelf: 'flex-start',
  },
  succes: {
    padding: `${spacing.sm + 4}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: 'rgba(20,200,120,0.1)',
    border: '1px solid rgba(20,200,120,0.3)',
    color: '#4DFFA8',
    fontSize: fontSize.sm,
  },
  erreur: {
    padding: `${spacing.sm + 4}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: 'rgba(244,98,42,0.1)',
    border: '1px solid rgba(244,98,42,0.3)',
    color: colors.error,
    fontSize: fontSize.sm,
  },
  dangerZone: {
    background: 'rgba(244,98,42,0.05)',
    border: '1px solid rgba(244,98,42,0.2)',
    borderRadius: radius.xl,
    padding: spacing.xl,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
  },
  dangerTitle: {
    fontSize: fontSize.lg,
    fontWeight: font.weight.bold,
    color: colors.orangeLight,
  },
  dangerSub: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    lineHeight: 1.6,
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: spacing.lg,
  },
  modal: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.12)`,
    borderRadius: radius.xl,
    padding: spacing.xl,
    width: '100%',
    maxWidth: '420px',
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  modalTitle: {
    fontSize: fontSize.lg,
    fontWeight: font.weight.bold,
    color: colors.text,
  },
  modalSub: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    lineHeight: 1.6,
  },
}
