import { colors, fontSize, spacing, radius, font } from '../../utils/theme'

export const styles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: `${spacing.xl}px ${spacing.lg}px`,
    background: colors.bg,
    fontFamily: font.sans,
    position: 'relative',
    overflow: 'hidden',
  },
  orb1: {
    position: 'fixed',
    width: '500px',
    height: '500px',
    borderRadius: radius.full,
    background: 'radial-gradient(circle, rgba(42,125,225,0.15) 0%, transparent 70%)',
    top: '-150px',
    right: '-150px',
    pointerEvents: 'none',
  },
  orb2: {
    position: 'fixed',
    width: '400px',
    height: '400px',
    borderRadius: radius.full,
    background: 'radial-gradient(circle, rgba(244,98,42,0.1) 0%, transparent 70%)',
    bottom: '-100px',
    left: '-100px',
    pointerEvents: 'none',
  },
  container: {
    width: '100%',
    maxWidth: '520px',
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xl,
    position: 'relative',
    zIndex: 1,
  },
  logoSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: spacing.md,
  },
  logo: {
    width: '56px',
    height: '56px',
    borderRadius: radius.lg,
  },
  title: {
    fontSize: fontSize.title,
    fontWeight: font.weight.bold,
    color: colors.text,
    letterSpacing: '-0.5px',
    margin: 0,
  },
  subtitle: {
    fontSize: fontSize.md,
    color: colors.textMuted,
    margin: `${spacing.xs}px 0 0 0`,
    textAlign: 'center',
  },
  card: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.12)`,
    borderRadius: radius.xl,
    padding: spacing.xl,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  sectionTitle: {
    fontSize: fontSize.sm,
    fontWeight: font.weight.semibold,
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: '1.5px',
    paddingBottom: spacing.sm,
    borderBottom: `1px solid rgba(91,163,245,0.08)`,
  },
  erreur: {
    padding: `${spacing.sm + 4}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: 'rgba(244,98,42,0.1)',
    border: '1px solid rgba(244,98,42,0.3)',
    color: colors.error,
    fontSize: fontSize.sm,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  row: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: spacing.md,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  label: {
    fontSize: fontSize.sm,
    fontWeight: font.weight.medium,
    color: colors.textMuted,
  },
  input: {
    width: '100%',
    padding: `${spacing.sm + 6}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: colors.surface2,
    border: `1px solid rgba(91,163,245,0.15)`,
    color: colors.text,
    fontSize: fontSize.md,
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: font.sans,
  },
  inputWrapper: {
    position: 'relative',
    width: '100%',
  },
  eyeBtn: {
    position: 'absolute',
    right: '14px',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: colors.textMuted,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    zIndex: 2,
  },
  colorRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
  },
  colorPreview: {
    width: '44px',
    height: '44px',
    borderRadius: radius.md,
    border: `1px solid rgba(91,163,245,0.15)`,
    flexShrink: 0,
    cursor: 'pointer',
  },
  colorInput: {
    flex: 1,
    padding: `${spacing.sm + 6}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: colors.surface2,
    border: `1px solid rgba(91,163,245,0.15)`,
    color: colors.text,
    fontSize: fontSize.md,
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: font.sans,
  },
  uploadZone: {
    border: `2px dashed rgba(91,163,245,0.2)`,
    borderRadius: radius.md,
    padding: `${spacing.lg}px`,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: spacing.sm,
    cursor: 'pointer',
    transition: 'border-color 0.2s',
  },
  uploadText: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    textAlign: 'center',
  },
  uploadPreview: {
    width: '64px',
    height: '64px',
    borderRadius: radius.md,
    objectFit: 'cover',
  },
  btn: {
    width: '100%',
    padding: `${spacing.sm + 6}px`,
    borderRadius: radius.md,
    background: colors.blue,
    color: 'white',
    fontWeight: font.weight.semibold,
    fontSize: fontSize.md,
    border: 'none',
    cursor: 'pointer',
    marginTop: spacing.xs,
    transition: 'opacity 0.2s',
    fontFamily: font.sans,
  },
  footer: {
    textAlign: 'center',
    fontSize: fontSize.sm,
    color: colors.textMuted,
  },
  link: {
    color: colors.blueLight,
    fontWeight: font.weight.semibold,
    textDecoration: 'none',
  },
}
