import { colors, fontSize, spacing, radius, font } from '../../utils/theme'

export const styles = {
  container: {
    maxWidth: '500px',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xl,
  },
  scannerBox: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.12)`,
    borderRadius: radius.xl,
    overflow: 'hidden',
    position: 'relative',
  },
  scannerInner: {
    width: '100%',
    minHeight: '300px',
  },
  scannerOverlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    background: 'rgba(11,17,32,0.85)',
  },
  scannerOverlayText: {
    fontSize: fontSize.md,
    color: colors.textMuted,
    textAlign: 'center',
    padding: `0 ${spacing.lg}px`,
  },
  btnPrimary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacing.sm,
    padding: `${spacing.sm + 4}px ${spacing.xl}px`,
    borderRadius: radius.md,
    background: colors.blue,
    color: 'white',
    fontWeight: font.weight.semibold,
    fontSize: fontSize.md,
    border: 'none',
    cursor: 'pointer',
    fontFamily: font.sans,
    transition: 'opacity 0.2s',
  },
  btnDanger: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacing.sm,
    padding: `${spacing.sm + 4}px ${spacing.xl}px`,
    borderRadius: radius.md,
    background: 'rgba(244,98,42,0.15)',
    color: colors.orange,
    fontWeight: font.weight.semibold,
    fontSize: fontSize.md,
    border: `1px solid rgba(244,98,42,0.3)`,
    cursor: 'pointer',
    fontFamily: font.sans,
  },
  resultCard: (type) => ({
    background: colors.surface,
    border: `1px solid ${
      type === 'success' ? 'rgba(20,200,120,0.3)' :
      type === 'error' ? 'rgba(244,98,42,0.3)' :
      'rgba(91,163,245,0.12)'
    }`,
    borderRadius: radius.xl,
    padding: spacing.xl,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
  }),
  resultHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
  },
  resultIcon: (type) => ({
    width: '48px',
    height: '48px',
    borderRadius: radius.full,
    background: type === 'success' ? 'rgba(20,200,120,0.15)' : 'rgba(244,98,42,0.15)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  }),
  resultTitle: {
    fontSize: fontSize.lg,
    fontWeight: font.weight.bold,
    color: colors.text,
  },
  resultSub: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    marginTop: '2px',
  },
  pointsDisplay: {
    display: 'flex',
    gap: spacing.md,
    marginTop: spacing.xs,
  },
  pointBadge: (color) => ({
    flex: 1,
    padding: spacing.md,
    borderRadius: radius.md,
    background: color,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
  }),
  pointValue: {
    fontSize: fontSize.xxl,
    fontWeight: font.weight.bold,
    color: colors.text,
  },
  pointLabel: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
  },
  rewardBanner: {
    padding: `${spacing.md}px ${spacing.lg}px`,
    borderRadius: radius.md,
    background: 'rgba(244,98,42,0.1)',
    border: '1px solid rgba(244,98,42,0.3)',
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
    fontSize: fontSize.md,
    color: colors.orangeLight,
    fontWeight: font.weight.semibold,
  },
  manualSection: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.12)`,
    borderRadius: radius.xl,
    padding: spacing.xl,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  manualTitle: {
    fontSize: fontSize.md,
    fontWeight: font.weight.semibold,
    color: colors.text,
  },
  manualRow: {
    display: 'flex',
    flexDirection: window.innerWidth < 480 ? 'column' : 'row',
    gap: spacing.md,
  },
  input: {
    flex: 1,
    padding: `${spacing.sm + 4}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: colors.surface2,
    border: `1px solid rgba(91,163,245,0.15)`,
    color: colors.text,
    fontSize: fontSize.md,
    outline: 'none',
    fontFamily: font.sans,
  },
}
