import { colors, fontSize, spacing, radius, font } from '../../utils/theme'

export const styles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: `${spacing.xl}px ${spacing.lg}px`,
    background: colors.bg,
    fontFamily: font.sans,
    position: 'relative',
    overflow: 'hidden',
  },
  orb1: {
    position: 'fixed',
    width: '400px',
    height: '400px',
    borderRadius: radius.full,
    background: 'radial-gradient(circle, rgba(42,125,225,0.12) 0%, transparent 70%)',
    top: '-100px',
    right: '-100px',
    pointerEvents: 'none',
  },
  orb2: {
    position: 'fixed',
    width: '300px',
    height: '300px',
    borderRadius: radius.full,
    background: 'radial-gradient(circle, rgba(244,98,42,0.08) 0%, transparent 70%)',
    bottom: '-80px',
    left: '-80px',
    pointerEvents: 'none',
  },
  container: {
    width: '100%',
    maxWidth: '420px',
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xl,
    position: 'relative',
    zIndex: 1,
  },
  // ─── Carte fidélité ───────────────────────────────
  cardFidelite: (brandColor) => ({
    borderRadius: radius.xxl,
    overflow: 'hidden',
    position: 'relative',
    background: `linear-gradient(135deg, #1A3A6B 0%, #0F2444 60%, #0B1A2E 100%)`,
    boxShadow: '0 24px 60px rgba(0,0,0,0.5)',
    border: '1px solid rgba(91,163,245,0.15)',
  }),
  cardAbonnement: {
    borderRadius: radius.xxl,
    overflow: 'hidden',
    position: 'relative',
    background: 'linear-gradient(135deg, #1A0A00 0%, #2D1205 50%, #1A0A00 100%)',
    boxShadow: '0 24px 60px rgba(0,0,0,0.5)',
    border: '1px solid rgba(244,98,42,0.2)',
  },
  cardTemps: {
    borderRadius: radius.xxl,
    overflow: 'hidden',
    position: 'relative',
    background: 'linear-gradient(135deg, #051510 0%, #0A2820 50%, #051510 100%)',
    boxShadow: '0 24px 60px rgba(0,0,0,0.5)',
    border: '1px solid rgba(20,200,120,0.2)',
  },
  cardOrb: (color) => ({
    position: 'absolute',
    width: '280px',
    height: '280px',
    borderRadius: radius.full,
    background: `radial-gradient(circle, ${color} 0%, transparent 70%)`,
    top: '-80px',
    right: '-60px',
    pointerEvents: 'none',
  }),
  cardTop: {
    padding: `${spacing.lg}px ${spacing.lg}px ${spacing.md}px`,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 1,
  },
  cardBusiness: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
  },
  cardLogo: {
    width: '44px',
    height: '44px',
    borderRadius: radius.md,
    objectFit: 'cover',
    background: 'rgba(255,255,255,0.1)',
    border: '1px solid rgba(255,255,255,0.15)',
  },
  cardLogoFallback: {
    width: '44px',
    height: '44px',
    borderRadius: radius.md,
    background: 'rgba(255,255,255,0.1)',
    border: '1px solid rgba(255,255,255,0.15)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: font.weight.bold,
    fontSize: fontSize.lg,
  },
  cardBusinessName: {
    fontSize: fontSize.md,
    fontWeight: font.weight.bold,
    color: 'white',
  },
  cardBusinessAddr: {
    fontSize: fontSize.xs,
    color: 'rgba(255,255,255,0.5)',
    marginTop: '2px',
  },
  typeBadge: (bg, color) => ({
    padding: '4px 10px',
    borderRadius: radius.full,
    background: bg,
    color: color,
    fontSize: '10px',
    fontWeight: font.weight.semibold,
    letterSpacing: '1px',
    textTransform: 'uppercase',
  }),
  // Points
  pointsSection: {
    padding: `4px ${spacing.lg}px ${spacing.md}px`,
    position: 'relative',
    zIndex: 1,
  },
  pointsLabel: {
    fontSize: '11px',
    color: 'rgba(255,255,255,0.4)',
    marginBottom: spacing.sm,
    letterSpacing: '0.5px',
  },
  pointsDots: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
    marginBottom: spacing.sm,
  },
  dot: (filled) => ({
    width: '26px',
    height: '26px',
    borderRadius: radius.full,
    background: filled
      ? 'linear-gradient(135deg, #F4622A 0%, #FF8A5B 100%)'
      : 'rgba(255,255,255,0.08)',
    border: filled ? 'none' : '1.5px solid rgba(255,255,255,0.12)',
    boxShadow: filled ? '0 2px 8px rgba(244,98,42,0.4)' : 'none',
  }),
  pointsCount: {
    fontSize: fontSize.sm,
    color: 'rgba(255,255,255,0.6)',
  },
  // Barre progression abonnement
  progressSection: {
    padding: `4px ${spacing.lg}px ${spacing.md}px`,
    position: 'relative',
    zIndex: 1,
  },
  progressHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: spacing.sm,
  },
  progressLabel: {
    fontSize: '11px',
    color: 'rgba(255,255,255,0.4)',
  },
  progressCount: {
    fontSize: fontSize.xl,
    fontWeight: font.weight.bold,
    color: 'white',
  },
  progressBarBg: {
    height: '8px',
    background: 'rgba(255,255,255,0.08)',
    borderRadius: radius.full,
    overflow: 'hidden',
  },
  progressBarFill: (pct) => ({
    height: '100%',
    width: pct + '%',
    background: 'linear-gradient(90deg, #F4622A 0%, #FF8A5B 100%)',
    borderRadius: radius.full,
    boxShadow: '0 0 12px rgba(244,98,42,0.5)',
  }),
  // Expiry
  expirySection: {
    padding: `4px ${spacing.lg}px ${spacing.md}px`,
    position: 'relative',
    zIndex: 1,
  },
  expiryLabel: {
    fontSize: '11px',
    color: 'rgba(255,255,255,0.4)',
    marginBottom: spacing.sm,
  },
  expiryDate: {
    fontSize: fontSize.xxl,
    fontWeight: font.weight.bold,
    color: 'white',
    letterSpacing: '-1px',
  },
  expiryRemaining: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    marginTop: spacing.sm,
    background: 'rgba(20,200,120,0.1)',
    border: '1px solid rgba(20,200,120,0.2)',
    borderRadius: radius.full,
    padding: '4px 12px',
    fontSize: fontSize.sm,
    color: '#4DFFA8',
  },
  // Divider
  divider: {
    height: '1px',
    background: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.08), transparent)',
    margin: `0 ${spacing.lg}px`,
    position: 'relative',
    zIndex: 1,
  },
  // Bottom carte
  cardBottom: {
    padding: `${spacing.md}px ${spacing.lg}px ${spacing.lg}px`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 1,
  },
  clientLabel: {
    fontSize: '10px',
    color: 'rgba(255,255,255,0.35)',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    marginBottom: '4px',
  },
  clientName: {
    fontSize: fontSize.lg,
    fontWeight: font.weight.bold,
    color: 'white',
  },
  serial: {
    fontFamily: font.mono,
    fontSize: '10px',
    color: 'rgba(255,255,255,0.3)',
    marginTop: '4px',
  },
  qrBox: {
    width: '68px',
    height: '68px',
    background: 'white',
    borderRadius: radius.md,
    padding: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrImg: {
    width: '100%',
    height: '100%',
  },
  // Reward banner
  rewardBanner: {
    padding: `${spacing.sm}px ${spacing.md}px`,
    margin: `0 ${spacing.lg}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: 'rgba(244,98,42,0.15)',
    border: '1px solid rgba(244,98,42,0.3)',
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    fontSize: fontSize.sm,
    color: '#FF8A5B',
    fontWeight: font.weight.semibold,
    position: 'relative',
    zIndex: 1,
  },
  // Wallet button
  walletBtn: {
    width: '100%',
    padding: `${spacing.md}px`,
    borderRadius: radius.md,
    background: '#1A1A1A',
    color: 'white',
    fontWeight: font.weight.semibold,
    fontSize: fontSize.md,
    border: '1px solid rgba(255,255,255,0.1)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    fontFamily: font.sans,
    textDecoration: 'none',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
  },
  sectionTitle: {
    fontSize: fontSize.md,
    fontWeight: font.weight.semibold,
    color: colors.text,
  },
  historiqueItem: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.08)`,
    borderRadius: radius.md,
    padding: `${spacing.md}px ${spacing.lg}px`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  historiqueAction: {
    fontSize: fontSize.sm,
    color: colors.text,
    fontWeight: font.weight.medium,
  },
  historiqueDate: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    marginTop: '2px',
  },
  historiqueBadge: (type) => ({
    fontSize: fontSize.xs,
    fontWeight: font.weight.semibold,
    padding: '3px 8px',
    borderRadius: radius.full,
    background: type === 'ADD_POINT' ? 'rgba(42,125,225,0.12)' :
                type === 'REDEEM' ? 'rgba(20,200,120,0.12)' :
                type === 'USE_SEANCE' ? 'rgba(244,98,42,0.12)' :
                'rgba(91,163,245,0.08)',
    color: type === 'ADD_POINT' ? '#5BA3F5' :
           type === 'REDEEM' ? '#4DFFA8' :
           type === 'USE_SEANCE' ? '#FF8A5B' :
           colors.textMuted,
  }),
}
