import { colors, fontSize, spacing, radius, font } from '../../utils/theme'

export const styles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: `${spacing.xl}px ${spacing.lg}px`,
    background: colors.bg,
    fontFamily: font.sans,
    position: 'relative',
    overflow: 'hidden',
  },
  orb1: {
    position: 'fixed',
    width: '400px',
    height: '400px',
    borderRadius: radius.full,
    background: 'radial-gradient(circle, rgba(42,125,225,0.12) 0%, transparent 70%)',
    top: '-100px',
    right: '-100px',
    pointerEvents: 'none',
  },
  orb2: {
    position: 'fixed',
    width: '300px',
    height: '300px',
    borderRadius: radius.full,
    background: 'radial-gradient(circle, rgba(244,98,42,0.08) 0%, transparent 70%)',
    bottom: '-80px',
    left: '-80px',
    pointerEvents: 'none',
  },
  container: {
    width: '100%',
    maxWidth: '420px',
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xl,
    position: 'relative',
    zIndex: 1,
  },
  proHeader: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: spacing.md,
    textAlign: 'center',
  },
  proLogo: {
    width: '72px',
    height: '72px',
    borderRadius: radius.xl,
    objectFit: 'cover',
    border: `2px solid rgba(91,163,245,0.2)`,
  },
  proLogoFallback: {
    width: '72px',
    height: '72px',
    borderRadius: radius.xl,
    background: colors.blue,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: font.weight.bold,
    fontSize: fontSize.xxl,
    border: `2px solid rgba(91,163,245,0.2)`,
  },
  proName: {
    fontSize: fontSize.xxl,
    fontWeight: font.weight.bold,
    color: colors.text,
    letterSpacing: '-0.5px',
  },
  proAddr: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    marginTop: '2px',
  },
  rewardBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacing.sm,
    padding: `${spacing.xs + 2}px ${spacing.md}px`,
    borderRadius: radius.full,
    background: 'rgba(244,98,42,0.1)',
    border: '1px solid rgba(244,98,42,0.25)',
    color: colors.orangeLight,
    fontSize: fontSize.sm,
    fontWeight: font.weight.medium,
    marginTop: spacing.xs,
  },
  card: {
    background: colors.surface,
    border: `1px solid rgba(91,163,245,0.12)`,
    borderRadius: radius.xl,
    padding: spacing.xl,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  cardTitle: {
    fontSize: fontSize.lg,
    fontWeight: font.weight.bold,
    color: colors.text,
  },
  cardSub: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    marginTop: '4px',
    lineHeight: 1.5,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  label: {
    fontSize: fontSize.sm,
    fontWeight: font.weight.medium,
    color: colors.textMuted,
  },
  input: {
    width: '100%',
    padding: `${spacing.sm + 6}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: colors.surface2,
    border: `1px solid rgba(91,163,245,0.15)`,
    color: colors.text,
    fontSize: fontSize.md,
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: font.sans,
  },
  btn: {
    width: '100%',
    padding: `${spacing.sm + 6}px`,
    borderRadius: radius.md,
    background: colors.blue,
    color: 'white',
    fontWeight: font.weight.semibold,
    fontSize: fontSize.md,
    border: 'none',
    cursor: 'pointer',
    fontFamily: font.sans,
    transition: 'opacity 0.2s',
  },
  erreur: {
    padding: `${spacing.sm + 4}px ${spacing.md}px`,
    borderRadius: radius.md,
    background: 'rgba(244,98,42,0.1)',
    border: '1px solid rgba(244,98,42,0.3)',
    color: colors.error,
    fontSize: fontSize.sm,
  },
  notFound: {
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: spacing.lg,
    padding: spacing.xl,
  },
  notFoundTitle: {
    fontSize: fontSize.xl,
    fontWeight: font.weight.bold,
    color: colors.text,
  },
  notFoundSub: {
    fontSize: fontSize.md,
    color: colors.textMuted,
  },
}
